# Generated by Django 4.2.1 on 2023-05-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField()),
                ('priority', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
