# Generated by Django 4.2.1 on 2023-05-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='desc',
            field=models.CharField(default='No description', max_length=300),
        ),
    ]
