# Generated by Django 4.2.1 on 2023-05-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0003_alter_tasks_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='assigned_to',
            field=models.CharField(default='self', max_length=50),
        ),
        migrations.AddField(
            model_name='tasks',
            name='completed',
            field=models.CharField(default='Not completed', max_length=10),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(default='High', max_length=10),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
